CraftyKnockout/CraftyKnockoutMvc/Controllers/AnalysisController.cs
using System.Web.Mvc;

namespace CraftyKnockoutMvc.Controllers
{
    public class AnalysisController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Part III - Why use KnockoutJS?";
            ViewBag.Message = "So what are the good bad and ugly parts of KnockoutJS?";

            return View();
        }


        public ActionResult Comparisons()
        {
            ViewBag.Title = "Part III - Alternatives to KnockoutJS?";
            ViewBag.Message = "As with all *JS libraries there are competitors this section will discuss some of these.";

            return View();
        }
	}
}

CraftyKnockout/CraftyKnockoutMvc/Controllers/GettingStartedController.cs
using System.Web.Mvc;

namespace CraftyKnockoutMvc.Controllers
{
    public class GettingStartedController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Part I - Getting started with KnockoutJS";
            ViewBag.Message = "An introduction to the KnockoutJS basics. A reminder for those familiar and an introduction for the uninitiated.";
            return View();
        }

        public ActionResult Resources()
        {
            return View();
        }

        public ActionResult HelloCraftyCoders()
        {
            return View();
        }

        public ActionResult Observable()
        {
            return View();
        }

        public ActionResult ObservableArray()
        {
            return View();
        }

        public ActionResult Computed()
        {
            return View();
        }
	}
}

CraftyKnockout/CraftyKnockoutMvc/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CraftyKnockoutMvc.Controllers
{
    public class HomeController : Controller
    {
        const string ApplicationAbstract = "A look into crafting web application with KnockoutJS and ASP.NET MVC. Discussing what knockout brings to the toolbox and when to use it.";

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            ViewBag.Abstract = ApplicationAbstract;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Title = "About Crafty Knockout";
            ViewBag.Message = "Crafty Knockout is an ASP.NET application created to facilitate a presentation about KnockoutJS";
            ViewBag.Abstract = ApplicationAbstract;

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Title = "Contact";
            ViewBag.Message = "This presentation application has been created by Steve Forth";

            return View();
        }
    }
}

CraftyKnockout/CraftyKnockoutMvc/Controllers/IntegrationWithMvcController.cs
using System.Web.Helpers;
using CraftyKnockoutMvc.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using CraftyKnockoutMvc.Attributes;
using CraftyKnockoutMvc.Repository;
using System.Diagnostics;
using System;

namespace CraftyKnockoutMvc.Controllers
{
    public class IntegrationWithMvcController : Controller
    {
        private readonly IRepository<FamousCoder> famousCoderRepository;

        public IntegrationWithMvcController(IRepository<FamousCoder> coderRepository)
        {
            famousCoderRepository = coderRepository;
            famousCoderRepository.SeedRepository();
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Part II - Getting started with KnockoutJS";
            ViewBag.Message = "KnockoutJS can be a very useful way to extend the functionality of an MVC web application. In this part we will explore some basic techniques to integrate KnockoutJS within an MVC.";
            return View();
        }

        public ActionResult HallOfFame()
        {
            var model = new HallOfFameModel();

            var listOfFamousCoders = famousCoderRepository.GetAll().OrderBy(m => m.FameScore * -1);

            foreach (var coder in listOfFamousCoders)
            {
                model.FamousCoders.Add(coder);
            }

            return View(model);
        }


        public ActionResult HallOfFameAjax()
        {
            return View();
        }

        [HttpGet]
        public JsonResult HallOfFameAjaxModel()
        {

            //For illustration I want to slow the data return down a bit.
            System.Threading.Thread.Sleep(2000);


            var model = new HallOfFameModel();

            var listOfFamousCoders = famousCoderRepository.GetAll().OrderBy(m => m.FameScore * -1);

            foreach (var coder in listOfFamousCoders)
            {
                model.FamousCoders.Add(coder);
            }

            // Use Newtonsoft to encode the class as a JSON. 
            var jsonEncodedModel = Newtonsoft.Json.JsonConvert.SerializeObject(model);

            //Return a JsonResult. You must included the behavior or else it does not get back to the client
            return Json(jsonEncodedModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditHallOfFame()
        {
            var listOfFamousCoders = famousCoderRepository.GetAll().AsEnumerable();

           return View(listOfFamousCoders);
        }


        [HttpPost]
        public ActionResult EditHallOfFame([FromJson] IList<FamousCoder> model)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in model)
                {
                    Debug.WriteLine("CoderName: {0}; Famous For:{1}; Scored: {2}", item.CoderName, item.FamousFor, item.FameScore);
                }

                famousCoderRepository.UpdateToMatchList(model);
            }

            return RedirectToAction("EditHallOfFame");
        }

        [HttpGet]
        public ActionResult KnockoutIsland()
        {
            var model = new KnockoutIslandModel();
            model.Event = new Event();
            model.Event.Speakers = new List<FamousCoder>();
            model.PossibleSpeakers = famousCoderRepository.GetAll().AsEnumerable();

            return View(model);
        }

        [HttpPost]
        public ActionResult KnockoutIsland(KnockoutIslandModel model)
        {
            if (model.Event.Speakers != null)
            {
                foreach (var speaker in model.Event.Speakers)
                {
                    Debug.WriteLine("CoderName: {0}; Session Name: {1}; ", speaker.CoderName, speaker.FamousFor);
                }
            }

            return View("EventView", model);
        }
	}
}

CraftyKnockout/CraftyKnockoutMvc/Views/Home/About.cshtml
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<p>@ViewBag.Abstract</p>

<p>Get the code used from <a href="https://github.com/Steve4th/CraftyKnockout">github.com/Steve4th/CraftyKnockout</a></p>

CraftyKnockout/CraftyKnockoutMvc/Views/Home/Contact.cshtml
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<address>
    <strong>Email:</strong>   <a href="mailto:Support@example.com">steveforth@hotmail.com</a><br />
    <strong>Twitter:</strong> <a href="https://twitter.com/sforth">@@sforth</a>
</address>

CraftyKnockout/CraftyKnockoutMvc/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>A Crafty Knockout</h1>
    <p class="lead">
        Crafty Knockout is an ASP.NET application created to facilitate a presentation about KnockoutJS
    </p>
    <p>@ViewBag.Abstract</p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started with KnockoutJS</h2>
        <p>
            An introduction to the KnockoutJS basics. A reminder for those familiar and an introduction for the uninitiated.
        </p>
        <p>
            @Html.ActionLink("Goto Part I >>", "Index", "GettingStarted", null, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Embedding in a MVC application</h2>
        <p>
            KnockoutJS can be a very useful way to extend the functionality of an MVC web application.
            It allows you to move towards a more interactive UI without the complexity and rethinking that a full SPA requires.
            In this section we will explore some basic techniques to integrate KnockoutJS within MVC.
        </p>
        <p>
            @Html.ActionLink("Goto Part II >>", "Index", "IntegrationWithMvc", null, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Why use KnockoutJS?</h2>
        <p>As with all *JS libraries there are competitors, advantages and disadvantages; this section will discuss some of these.</p>
        <p>
            @Html.ActionLink("Goto Part III >>", "Index", "Analysis", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>